Portfolio setup mobile version
DebbyBud/project1 pull request #1
Opened 2022-08-25 09:37 UTC by DebbyBud

In this commit, i worked on the "recent work" page, added the CSS appropriate.

2022-08-25 09:40 UTC, HAMMAS-SALEEM reviewed
# Invalid Pull Request :red_circle: :traffic_light: :rotating_light:

## Hey @DebbyBud :wave: 

**You have made a great effort on your project :blush: and I can see that but unfortunately I can not proceed with a code review of your pull request due to the following reasons :receipt:**

- [ ] Your Linters are not passing. Please fix them :+1:
- [ ] You don't have a descriptive summary for your pull request. Please make it descriptive :+1:

### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 13:13 UTC, Reem-lab requested changes
# Hi @DebbyBud, 👋🏻👋🏻 

Good job so far! 🔥🔥🚀🚀💯💯
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅



## Required Changes ♻️
_Check the comments under the review._
- [ REQUIRED ] Please add the `README` file from microverse template and customize your infformation into it and don't forget to add the `MIT` to it, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it :wink:
>
> > The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. :100:
>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 13:13 UTC, Reem-lab commented on index.html
> +            </article>
- [ ] Great job but I think you should adjust your width for the whole page to let me be able to review it so kindly fix your width to match the figma design as much as possible you can use minimum mobile screen size should be 375px. so kindly fix it 🙏🏻✅

- Your design
![image](https://user-images.githubusercontent.com/58553711/186671755-048dc2a0-937d-4448-ba5d-c684afeda71b.png)

- Figma design
![image](https://user-images.githubusercontent.com/58553711/186671974-74074ec4-7214-4d17-ba0f-d2e36a0f9df2.png)

2022-08-25 13:13 UTC, Reem-lab commented on index.html
> +                </div>
## Kindly make it in all the cards 💯🙏🏻🙏🏻✅✅✅🚀
- [ ] Great job but I think you should adjust your width for the whole page to let me be able to review it so kindly fix your width to match the figma design as much as possible you can use minimum mobile screen size should be 375px. so kindly fix it 🙏🏻✅

- Your design
![image](https://user-images.githubusercontent.com/58553711/186672108-9b8566a9-bacd-49bb-b376-0e66ebd4f1c9.png)

- Figma design
![image](https://user-images.githubusercontent.com/58553711/186672498-85e56491-da25-47db-a655-e3d6e89c0f23.png)

2022-08-25 13:13 UTC, Reem-lab commented on index.html
> +
- [ ] I think you didn't implement the "About myself" section (placed after the projects and before the contact form) so kindly work on it since it is one of the requirements so please add so far this milestone is for the projects section and about me section ✅🙏🏻🙏🏻💯💯

2022-08-25 14:24 UTC, ShahierNashaat requested changes
Hi @DebbyBud, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 14:24 UTC, ShahierNashaat commented on index.html
> +
- [ ] Please implement the "About myself" section as the previous code reviewer mentioned.

2022-08-25 14:24 UTC, ShahierNashaat commented on index.html
> +            </article>
- [ ] As the previous code reviewer mentioned that you should adjust the width of the cards to make them match the Figma design.

2022-08-25 20:09 UTC, tugsem requested changes
Hi @DebbyBud , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

While you made great effort to implement the changes, I see you are missing  requirements which both of the reviewers adressed earlier. Please pay attention to project requirements sice they are mandotory and important for your coding skills. Before submitting another review make sure you have: 
- [ ] About me section set up correctly
- [ ] Correct widths and spacings between elements

Your elements overflow the screen and overlaps the other elements:
![image](https://user-images.githubusercontent.com/91486791/186758201-00c9a89e-4af7-46a6-bc81-0cf6fdaab8d3.png)

I suggest you to take your time and work on these before you proceeding next block. Since these are the core skills that every programmer must have. Good luck!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-26 11:42 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @DebbyBud , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 11:42 UTC, bobb-Rob commented on index.html
> +        </div>
- [ ] I noticed that you have not been able to apply correct widths and spacing between elements, ultimately organizing your project so that it resembles the Figma design. 

     👇  I have tried to identify a few things that are the issues:
   - Your `header` tag is wrapping sections that it should not. The `<header>` element typically is used to identify content that precedes the primary content of the web page and often contains the website logo, navigation elements, search forms, and similar content that is duplicated across all or most pages of a website.  [Read more here](https://html.com/tags/header/#:~:text=The%20element%20is%20used,most%20pages%20of%20a%20website.).
   👉 **Action to take:** Kindly use the `<header>` element as shown below:
```
<header class="head">
        <div class="topnav" id="myTopnav">
            <a href="#debby" class="active">Debby</a>
            <nav>
                <div class="others">
                    <span class="line1"></span>
                    <span class="line2"></span>
                    <span class="line3"></span>
                   **You should have your mobile hamburger button here**
                </div>
            </nav>
        </div>
</header>
```
   - The section element `<section class="header">` that you currently have as a child the `<header>` element should be a sibling of the `header` element and not a child.
   - The background of the headline section should not be an `img` tag but it should be applied using CSS background property ```background-image: URL(image-path);``` on the section. 

**_While I see a lot of other issues than cannot be explain easily through writing. I can help you point out suggestions that can help you fix this easily. You can reach me via zoom or on whatsapp (+2347066736848), lets set up a zoom call and work on this._**

2022-08-26 17:14 UTC, frank1738 approved these changes
Hi @DebbyBud , 

Good work implementingchanges requested by the previous reviewer Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)

## Highlights
✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Descriptive PR 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 17:14 UTC, frank1738 commented on index.html
> +        </p>
- [OPTIONAL] Try to align your headline text to the center to give it a good look.

![image](https://user-images.githubusercontent.com/98453979/186957524-dae521d4-b1c8-47fe-8abc-ae12430db7c2.png)

2022-08-26 19:48 UTC, merged